using System.Collections.Generic;

namespace sellnet.Services
{
    public class UtilityService
    {
        public HashSet<string> Cities { get; } = new HashSet<string> {
            "Agrabad",
            "Bangla",
            "Barisal",
            "Bazar",
            "Chittagong",
            "Comilla",
            "Delta",
            "Dhaka",
            "Hossain",
            "Jessore",
            "Kabi",
            "Kazipur",
            "Mymensingh",
            "Narayanganj",
            "Rajshahi",
            "Tejgaon",
            "Uttara",
            "Barguna",
            "Barisāl",
            "Bhāndāria",
            "Bhola",
            "Burhānuddin",
            "Gaurnadi",
            "Jhalokati",
            "Lālmohan",
            "Mathba",
            "Mehendiganj",
            "Nālchiti",
            "Patuakhali",
            "Pirojpur",
            "Bandarban",
            "Bāndarban",
            "Bibir Hat",
            "Brahmanbaria",
            "Chandpur",
            "Chhāgalnāiya",
            "Cox's Bazar",
            "Cox’s Bāzār",
            "Feni",
            "Hājīganj",
            "Khagrachhari",
            "Lākshām",
            "Lakshmipur",
            "Lakshmīpur",
            "Manikchari",
            "Nabīnagar",
            "Noakhali",
            "Patiya",
            "Rāipur",
            "Rāmganj",
            "Rangamati",
            "Raojān",
            "Sandwīp",
            "Sātkania",
            "Teknāf",
            "Azimpur",
            "Bājitpur",
            "Bhairab Bāzār",
            "Char Bhadrāsan",
            "Char Golora",
            "Dohār",
            "Faridpur",
            "Farīdpur",
            "Gazipur",
            "Gopalganj",
            "Joymontop",
            "Khanbaniara",
            "Kishoregonj",
            "Kishorganj",
            "Madaripur",
            "Mādārīpur",
            "Manikganj",
            "Mirzāpur",
            "Munshiganj",
            "Nāgarpur",
            "Nārāyanganj",
            "Narsingdi",
            "Pālang",
            "Paltan",
            "Parvez Ali",
            "Parvez Ali Hossain",
            "Rajbari",
            "Ramnagar",
            "Sakhipur",
            "Sayani",
            "Shariatpur",
            "Sonārgaon",
            "Tangail",
            "Tāngāil",
            "Tungi",
            "Tungipāra",
            "Bagerhat",
            "Bhātpāra Abhaynagar",
            "Bherāmāra",
            "Chuadanga",
            "Jhenaidah",
            "Jhingergācha",
            "Kālia",
            "Kālīganj",
            "Kesabpur",
            "Khulna",
            "Kushtia",
            "Magura",
            "Meherpur",
            "Morrelgonj",
            "Narail",
            "Nowlamary",
            "Phultala",
            "Sarankhola",
            "Satkhira",
            "Sātkhira",
            "Ujalpur",
            "Uttar Char Fasson",
            "Gafargaon",
            "Jamalpur",
            "Jamālpur",
            "Muktāgācha",
            "Netrakona",
            "Sarishābāri",
            "Sherpur",
            "Bera",
            "Bogra",
            "Chapai Nababganj",
            "Ishurdi",
            "Joypur Hāt",
            "Joypurhat",
            "Mahasthangarh",
            "Naogaon",
            "Natore",
            "Nawābganj",
            "Pabna",
            "Pābna",
            "Pār Naogaon",
            "Puthia",
            "Rājshāhi",
            "Saidpur",
            "Shāhzādpur",
            "Shibganj",
            "Sirajganj",
            "Badarganj",
            "Chilmāri",
            "Dinajpur",
            "Dinājpur",
            "Gaibandha",
            "Kurigram",
            "Lalmonirhat",
            "Lalmonirhat District",
            "Nageswari",
            "Nilphamari Zila",
            "Panchagarh",
            "Parbatipur",
            "Pīrgaaj",
            "Rangpur",
            "Thakurgaon",
            "Thākurgaon",
            "Baniachang",
            "Chhātak",
            "Habiganj",
            "Jahedpur",
            "Maulavi Bāzār",
            "Maulvibazar",
            "Sunamganj",
            "Sylhet"
        };
        public HashSet<string> Divisions { get; } = new HashSet<string> {
            "Dhaka",
            "Chittagong",
            "Khulna",
            "Barisāl",
            "Rajshahi",
            "Rangpur",
            "Mymensingh",
            "Sylhet"
        };
    }
}